[tool.poetry]
name = "spearbrain"
version = "0.1.0"
description = "Spearfishing app"
authors = ["Konstantinos Palaiologos <konpaleo@hotmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.1"
pydantic = "^2.9.2"
pydantic-settings = "^2.9.1"
numpy = "^2.2.6"
pandas = "^2.3.0"
fastapi = "^0.115.12"
dotenv = "^0.9.9"
jwt = "^1.3.1"
passlib = "^1.7.4"
httpx = "^0.28.1"
uvicorn = "^0.34.3"
python-multipart = "^0.0.20"
